#FROM golang:1.21.6

#WORKDIR /app

#COPY go.mod .
#COPY main.go .

#to po tescie
#RUN go get
#RUN go build -o bin .

#ENTRYPOINT [ "/ap/bin" ]
FROM golang:1.21.6

WORKDIR /app

# Copy go.mod and go.sum files to the working directory
COPY go.mod .
COPY go.sum .

# Download dependencies
RUN go mod download

# Copy the entire project
COPY . .

# Build the application
RUN go build -o bin .

ENTRYPOINT [ "/app/bin" ]