apiVersion: v1
kind: Service
metadata:
  name: frontendv2-service
spec:
  selector:
    app: frontendv2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # Adjust to the port your Vue app is running
  type: LoadBalancer # Adjust based on your requirements
