apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue_appv3-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vue_appv3
  template:
    metadata:
      labels:
        app: vue_appv3
    spec:
      containers:
        - name: vue_appv3
          image: gcr.io/project-kuber/vue_appv3:latest
          ports:
            - containerPort: 3000
           env:
            - name: PORT
            value: "3000" 
